### ISSUE TITLE
NFImage component

### ISSUE THREAD

**Issue by wotori** [wotori-studio/nftext#15]
We need also image component, probably It could be based on text so we can use the same code for multiple purpose (and for 3D in the future). 
From the square sketch that @vzichv sugested I added how it could be for vertical and horizontal pictures.
![image](https://user-images.githubusercontent.com/10486621/157020181-77fc268f-e29f-4d39-a4ce-a49b34f47a89.png)

**Comment by vzichv** [comment]
Here is a design that is well suited to adapt to any kind of screens without any problems, and it seemed to us the most perfect look of all our ideas.
![ready](https://user-images.githubusercontent.com/65044775/157052415-d7ccd317-126d-4529-8e7e-4ad9fcf25af7.png)

**Comment by vzichv** [comment]
The component has been successfully developed, we are moving on to the stage of developing a universal modal window #10.
