### ISSUE TITLE
Modal window component

### ISSUE THREAD

**Issue by wotori** [wotori-studio/nftext#16]
Text modal window should allow user to see the whole text and images that are already created based on this text.
![image](https://user-images.githubusercontent.com/10486621/157020894-2e5035b5-4497-4c33-9d8d-b3b5e002f61f.png)

we have to keep in mind that we have 3 mediums (text, image, 3d) and for each of them we have a bit different interface but the core still the same.
![image](https://user-images.githubusercontent.com/10486621/157021119-dea6c19c-1217-4778-a6e8-8ed1d1ddb0bb.png)

Should It be a three different components or one universal? Or mb if It's better to make separate comps, they could share one style?

**Comment by vzichv** [comment]
It was decided to develop a universal modal window component that will accept certain parameters to correctly display information about our NFT components.

At the moment we are coordinating the design of the window.

**Comment by wotori** [comment]
modal update for 1st iteration 
![image](https://user-images.githubusercontent.com/10486621/158073545-ea3f032b-4940-4823-844e-71f8617a37ef.png)

**Comment by wotori** [comment]
Basic version of the modal is done. 
![image](https://user-images.githubusercontent.com/10486621/172240952-5cce702c-2b19-4c17-9728-e4e45d084857.png)
