### ISSUE TITLE
State management

### ISSUE THREAD

**Issue by wotori** [wotori-studio/nftext#17]
Do we need smth like [MobX](https://mobx.js.org/README.html) and how Is It better then Redux for example.
As I notice we still able to manage state with integrated into react features.
For example as I noticed there is a [context](https://reactjs.org/docs/context.html) to solve this. Mb we don't need additional dependencies and keep our app small-medium size and lightweight

some articles:
https://blog.openreplay.com/redux-alternatives-in-2021
https://blog.bitsrc.io/redux-react-alternatives-c1733793a339

**Comment by vzichv** [comment]
At the moment we have already imported MobX into our project.
