### ISSUE TITLE
Close modal interface

### ISSUE THREAD

**Issue by wotori** [wotori-studio/nftext#18]
can we close modal with click outside of modal. For me It seems faster and obvious.
![image](https://user-images.githubusercontent.com/10486621/157488150-5716bfb1-7cc7-4b6b-b330-c7c34d4a58f8.png)
p.s. cross for closing modal is not visible.
for some users It could be also useful so let's keep It along with the click outside of the modal

**Comment by vzichv** [comment]
The idea is good, I will implement it soon :)

**Comment by vzichv** [comment]
Cross icon display issue:
The cross is displayed during local development, but disappears in production. Why this happens is not known yet.

Solution:
It was decided to draw the cross using the SASS preprocessor.

It was decided to create a separate component with a modal window.

Also, the implementation of closing the modal window by clicking outside of it has already been developed. As soon as we solve the problems with displaying text in NFText (#21)  and some problems on the server, I will create a branch for the development of the modal window and in the shortest possible time I will be engaged in the full development of the component.
