### ISSUE TITLE
Untie the interface from the blockchain

### ISSUE THREAD

**Issue by wotori** [wotori-studio/nftext#26]
We faced a network crash problem, which led to the fact that we cannot develop the project.
We need to decouple the functionality from the network, create a data structure with 3 texts, 3 pictures and 3 3D models, and draw our interface based on them, as if we are online.

In .env we need a setting that will determine where we are reading data from (offline/online mode. mb development=true/false)

seems we need and array of [this](https://github.com/wotori-studio/NFText/blob/772cd6dccf258251de09bfe61448e3f971281c46/src/mint/NftBrowser.tsx#L52-L59) objects

**Comment by vzichv** [comment]
This system was implemented using MobX global states.
